// SPDX-FileCopyrightText: 2026 Jofi contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

// Typed API client from the backend's OpenAPI contract (ADR-0016). Run `pnpm api`; the output in
// src/api/generated is git-ignored and regenerated by `pnpm typecheck`, `pnpm test` and `pnpm build`.
// Docs: https://orval.dev/docs/reference/configuration/output

import { defineConfig } from "orval";

const input = { target: "../api/openapi.json" };

export default defineConfig({
  jofi: {
    input,
    output: {
      mode: "single",
      target: "src/api/generated/jofi.ts",
      client: "react-query",
      httpClient: "fetch",
      override: {
        mutator: { path: "src/api/fetcher.ts", name: "apiFetch" },
        fetch: { includeHttpResponseReturnType: false },
      },
    },
  },
  jofiZod: {
    input,
    output: {
      mode: "single",
      target: "src/api/generated/jofi.zod.ts",
      client: "zod",
    },
  },
});
