// SPDX-FileCopyrightText: 2026 Jofi contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

package io.github.scriptibus.jofi.system.adapter.buildinfo

import io.github.scriptibus.jofi.system.application.port.BuildInfoPort
import org.springframework.beans.factory.ObjectProvider
import org.springframework.boot.info.BuildProperties
import org.springframework.stereotype.Component

/**
 * Reads the version from `META-INF/build-info.properties` (generated by the Spring Boot Gradle
 * plugin). Falls back to [UNKNOWN_VERSION] when the file is absent, e.g. in an IDE run.
 */
@Component
class BuildPropertiesAdapter(
    private val buildProperties: ObjectProvider<BuildProperties>,
) : BuildInfoPort {
    override fun applicationVersion(): String = buildProperties.ifAvailable?.version ?: UNKNOWN_VERSION

    companion object {
        const val UNKNOWN_VERSION: String = "unknown"
    }
}
