// SPDX-FileCopyrightText: 2026 Jofi contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

// The icon set (Lucide, ISC). Icons are decorative: lucide hides them from assistive technology
// unless they get an accessible name, so always pair them with visible text or a label.

export type { LucideIcon as Icon } from "lucide-react";
export {
  ArchiveRestore as RestoreIcon,
  ArrowDown as MoveDownIcon,
  ArrowLeft as BackIcon,
  ArrowUp as MoveUpIcon,
  Ban as BlacklistedIcon,
  Briefcase as ApplicationsIcon,
  Building as CompaniesIcon,
  Check as CheckIcon,
  ChevronDown as ChevronDownIcon,
  ChevronDown as SortDescendingIcon,
  ChevronsUpDown as SortableIcon,
  ChevronUp as SortAscendingIcon,
  CircleAlert as WarningIcon,
  CircleCheck as SuccessIcon,
  Clock as OverdueIcon,
  Download as DownloadIcon,
  Globe as WebIcon,
  Info as InfoIcon,
  KeyRound as KeyIcon,
  LayoutDashboard as DashboardIcon,
  ListChecks as TasksIcon,
  Lock as FrozenIcon,
  LogOut as LogOutIcon,
  Mail as EmailIcon,
  MailOpen as ReadIcon,
  MessageCircle as ChatIcon,
  MessageSquareText as OtherChannelIcon,
  Pencil as EditIcon,
  Phone as PhoneIcon,
  Plus as AddIcon,
  RefreshCw as RefreshIcon,
  Search as SearchIcon,
  Settings as SettingsIcon,
  Share2 as ShareIcon,
  Star as FavouriteIcon,
  Trash2 as DeleteIcon,
  TriangleAlert as ErrorIcon,
  Undo2 as UndoIcon,
  Upload as UploadIcon,
  Users as ContactsIcon,
  WifiOff as OfflineIcon,
  X as CloseIcon,
} from "lucide-react";
