// SPDX-FileCopyrightText: 2026 Jofi contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

// The icon set (Lucide, ISC). Icons are decorative: lucide hides them from assistive technology
// unless they get an accessible name, so always pair them with visible text or a label.

export type { LucideIcon as Icon } from "lucide-react";
export {
  ArchiveRestore as RestoreIcon,
  ArrowDown as MoveDownIcon,
  ArrowLeft as BackIcon,
  ArrowRightLeft as MoveIcon,
  ArrowUp as MoveUpIcon,
  Ban as BlacklistedIcon,
  Bot as AiIcon,
  Briefcase as ApplicationsIcon,
  Building as CompaniesIcon,
  Calendar as CalendarIcon,
  CalendarClock as InterviewIcon,
  Check as CheckIcon,
  ChevronDown as ChevronDownIcon,
  ChevronDown as SortDescendingIcon,
  ChevronLeft as PreviousIcon,
  ChevronRight as NextIcon,
  ChevronsUpDown as SortableIcon,
  ChevronUp as SortAscendingIcon,
  CircleAlert as WarningIcon,
  CircleCheck as SuccessIcon,
  Clock as OverdueIcon,
  Download as DownloadIcon,
  Ellipsis as MoreIcon,
  FileText as DescriptionIcon,
  Globe as WebIcon,
  GripVertical as DragHandleIcon,
  Info as InfoIcon,
  KeyRound as KeyIcon,
  LayoutDashboard as DashboardIcon,
  Link as LinkIcon,
  ListChecks as TasksIcon,
  Lock as FrozenIcon,
  LogOut as LogOutIcon,
  Mail as EmailIcon,
  MailOpen as ReadIcon,
  MessageCircle as ChatIcon,
  MessageSquareText as OtherChannelIcon,
  Pencil as EditIcon,
  Phone as PhoneIcon,
  Plug as ExternalClientIcon,
  Plus as AddIcon,
  Radar as ScannerIcon,
  RefreshCw as RefreshIcon,
  Search as SearchIcon,
  Server as SystemIcon,
  Settings as SettingsIcon,
  Share2 as ShareIcon,
  Star as FavouriteIcon,
  Trash2 as DeleteIcon,
  TriangleAlert as ErrorIcon,
  Undo2 as UndoIcon,
  Unlink as UnlinkIcon,
  Upload as UploadIcon,
  User as UserIcon,
  Users as ContactsIcon,
  WifiOff as OfflineIcon,
  X as CloseIcon,
} from "lucide-react";
