// SPDX-FileCopyrightText: 2026 Jofi contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

// The web app manifest and theme colours, built from src/styles/tokens.css so the installed app,
// the browser's title bar and the UI share one palette. Used by vite.config.ts (node) and tested
// in vitest; only a type import, so it compiles under both tsconfigs.

import type { ManifestOptions } from "vite-plugin-pwa";

/** The value of `--<name>` inside the first rule whose selector is exactly `selector`. */
export function tokenValue(css: string, selector: string, name: string): string {
  const start = css.indexOf(`${selector} {`);
  if (start === -1) throw new Error(`tokens.css has no rule "${selector}"`);
  const block = css.slice(css.indexOf("{", start) + 1, css.indexOf("}", start));
  // Plain string matching per declaration: no regular expression built from the name.
  const property = `--${name}:`;
  const declaration = block
    .split(";")
    .map((part) => part.trim())
    .find((part) => part.startsWith(property));
  const value = declaration?.slice(property.length).trim();
  if (!value) throw new Error(`tokens.css rule "${selector}" has no --${name}`);
  return value;
}

export interface ThemeColours {
  light: { background: string; foreground: string; accent: string };
  dark: { background: string };
}

export function themeColours(css: string): ThemeColours {
  return {
    light: {
      background: tokenValue(css, ":root", "bg"),
      foreground: tokenValue(css, ":root", "fg"),
      accent: tokenValue(css, ":root", "accent"),
    },
    dark: { background: tokenValue(css, ':root[data-theme="dark"]', "bg") },
  };
}

/** Icons in public/icons, generated by scripts/generate-pwa-icons.ts. */
export const PWA_ICONS: ManifestOptions["icons"] = [
  { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
  { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
  { src: "/icons/icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
];

export type WebAppManifest = Partial<ManifestOptions> &
  Pick<
    ManifestOptions,
    "name" | "start_url" | "scope" | "display" | "theme_color" | "icons" | "share_target"
  >;

/**
 * The manifest (vite-plugin-pwa writes it as manifest.webmanifest). `share_target` makes Jofi a
 * target of the system share sheet once installed: a GET to `/share?title=…&text=…&url=…`, which
 * the SPA shows (import handling: #34).
 */
export function webAppManifest(colours: ThemeColours): WebAppManifest {
  return {
    id: "/",
    name: "Jofi",
    short_name: "Jofi",
    description: "Self-hosted, AI-assisted job application manager",
    lang: "en",
    dir: "ltr",
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "any",
    background_color: colours.light.background,
    theme_color: colours.light.background,
    categories: ["productivity", "business"],
    icons: PWA_ICONS,
    share_target: {
      action: "/share",
      method: "GET",
      enctype: "application/x-www-form-urlencoded",
      params: { title: "title", text: "text", url: "url" },
    },
  };
}

/** `<meta name="theme-color">` per colour scheme, so the browser chrome follows light and dark. */
export function themeColourMeta(colours: ThemeColours): string {
  return [
    `<meta name="theme-color" media="(prefers-color-scheme: light)" content="${colours.light.background}" />`,
    `<meta name="theme-color" media="(prefers-color-scheme: dark)" content="${colours.dark.background}" />`,
  ].join("\n    ");
}
